print("I love python")
print(type("9"))
print(type([1,2,3,4]))
print(type((1, 2, 3, 4)))
print(type("ahmed"))
print(type(9))
print(type(10.9))
print(type({"key1": 1, "key2": 2}))
print(type(2 == 2))
help("keywords")